name: Download Cloudflare IPs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  download-ips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Run script to download IPs
        run: node .

      - name: Commit and push if changed
        run: |
          git config user.name "Sefinek Actions"
          git config user.email "sefinek.actions@gmail.com"
          git add cloudflare_ips
          git commit -m "✨ Update Cloudflare IPs" || echo "No changes to commit"
          git push
